# Generated by Django 2.2 on 2021-07-15 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issueBook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userissuing',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
