# Generated by Django 2.2 on 2021-07-16 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issueBook', '0002_auto_20210715_2001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userissuing',
            options={},
        ),
        migrations.RemoveField(
            model_name='userissuing',
            name='status',
        ),
    ]
